---
- name: Create logical volume group
  community.general.lvg:
    vg: data
    pvs: /dev/sdb

- name: Create logical volume
  community.general.lvol:
    vg: data
    lv: k3s
    size: 100%FREE

- name: Make filesystem
  community.general.filesystem:
    fstype: ext4
    dev: /dev/mapper/data-k3s

- name: Mount additional disk
  mount:
    state: mounted
    path: /var/lib/rancher/k3s
    fstype: ext4
    src: /dev/mapper/data-k3s
